export type SpacePropTypes = 'gap' | 'mt' | 'mb' | 'ml' | 'mr' | 'm' | 'my' | 'mx'
export type BreakPointTypes = '_' | 'sm' | 'md' | 'lg' | 'xl'
export type ColorTypes = 'black' | 'white' | 'primary' | 'secondary' | 'success' | 'error' | 'disable'
export type WidthTypes = 'max' | 'full'
export type SpaceTypes =
  | 'px'
  | '0'
  | '0.5'
  | '1'
  | '1.5'
  | '2'
  | '2.5'
  | '3'
  | '3.5'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '10'
  | '11'
  | '12'
  | '14'
  | '16'
  | '20'
  | '24'
  | '28'
  | '32'
  | '36'
  | '40'

export type FontSizeTypes =
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | '9xl'
  | '10xl'

export type FontWeightTypes = '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900'
